### PR TITLE
service/info: refactor by splitting into respective controllers

### PR DESCRIPTION
**Pull request by jevonyeoh**
## Description
While adding `info` for target, I decided to clean up the info service!

This refactor allows us to:
- have standardized service initialization via dependency injection across the board
- no central dependency knot in `info_service`
- no more lint warnings (`too-many-instance-attributes,too-many-lines,too-many-public-methods`) from `info_service`
- info logic for each API object lives more closely to its own service definition

This should also help speed up building of dependencies as controllers don't have to build `info_service`, which had a ton of dependencies in it.

## Type of Change

Label this pull request to place it under the correct category in Release Notes:

|        **Pull Request Label**         | **Category in Release Notes** |
|:-------------------------------------:|:-----------------------------:|
|       `enhancement`, `feature`        |          🚀 Features          |
| `bug`, `refactoring`, `bugfix`, `fix` |    🔧 Fixes & Refactoring     |
|       `build`, `ci`, `testing`        |    📦 Build System & CI/CD    |
|              `breaking`               |      💥 Breaking Changes      |
|            `documentation`            |       📝 Documentation        |
|            `dependencies`             |    ⬆️ Dependencies updates    |

## Checklist

- [ ] I have read the [`CODE_OF_CONDUCT.md`](https://github.com/featurebyte/featurebyte/blob/main/CODE_OF_CONDUCT.md) and [`CONTRIBUTING.md`](https://github.com/featurebyte/featurebyte/blob/main/CONTRIBUTING.md) guides.
- [ ] I have written tests for the changes made.
- [ ] I have written docstrings in [NumpyDoc format](https://numpydoc.readthedocs.io/en/latest/format.html#docstring-standard)
- [ ] I have labeled my Pull Request correctly

### CODE REVIEW

**Comment by gee-senbong** [comment]
The main reason why the info service is introduced is to avoid circular dependency (initially, the info logic is in the document service level). If info service takes long time to construct dependencies, should we just move the info extraction logic to the controller level? There is no more info service class, the info construction logic move to the controller's get info method. What do you think?

**Comment by jevonyeoh** [comment]
that's fine by me! happy to move the `get_*_info` implementations directly into the controller, vs putting them in the respective services.

**Comment by gee-senbong** [comment]
Should we move `feature` info & `feature_namespace` info from info service to the controller?

**Comment by jevonyeoh** [comment]
moved! 

i'll split the `test_info` file in a follow-up PR (moving the respective tests into their respective controllers) as well!

**Review by gee-senbong — APPROVED** [review]
LGTM. Thanks for cleaning this up! 👍

**Pull request merged**
