### PR TITLE
[RELEASE] Releasing 2.0.0

### PR DESCRIPTION
**Pull request by bushwhackr**
### 🛑 Breaking Changes

+ `service` Remove default values for mandatory arguments in aggregation methods such as aggregate_over.
    The value_column parameter must now be provided.

### 💡 Enhancements

+ `linting` Using ruff as the linter for the project
+ `package` Upgrade Pydantic to V2

### ⚠️  Deprecations

+ `dependencies` Deprecation of `sasl` library to support python 3.11

### 🐛 Bug Fixes

+ `service` Fix feature metadata extraction throwing KeyError during feature info retrieval
+ `session` Handle schema and table listing for catalogs without information schema in DataBricks Unity.

## Type of Change

Label this pull request to place it under the correct category in Release Notes:

|        **Pull Request Label**         | **Category in Release Notes** |
|:-------------------------------------:|:-----------------------------:|
|       `enhancement`, `feature`        |          🚀 Features          |
| `bug`, `refactoring`, `bugfix`, `fix` |    🔧 Fixes & Refactoring     |
|       `build`, `ci`, `testing`        |    📦 Build System & CI/CD    |
|              `breaking`               |      💥 Breaking Changes      |
|            `documentation`            |       📝 Documentation        |
|            `dependencies`             |    ⬆️ Dependencies updates    |

## Checklist

- [ ] I have read the [`CODE_OF_CONDUCT.md`](https://github.com/featurebyte/featurebyte/blob/main/CODE_OF_CONDUCT.md) and [`CONTRIBUTING.md`](https://github.com/featurebyte/featurebyte/blob/main/CONTRIBUTING.md) guides.
- [ ] I have written tests for the changes made.
- [ ] I have written docstrings in [NumpyDoc format](https://numpydoc.readthedocs.io/en/latest/format.html#docstring-standard)
- [ ] I have labeled my Pull Request correctly

### CODE REVIEW

**Comment by YS-L** [comment]
We should include changelog from this PR: https://github.com/featurebyte/featurebyte/pull/2468/files

* Remove default values for mandatory arguments in aggregation methods such as `aggregate_over`. The `value_column` parameter must now be provided.

**Comment by YS-L** [comment]
Sorry, it's actually the first item in the changelog but I missed it. Would be good to add the note on `value_column`.

**Comment by YS-L** [comment]
Should that be listed under a "breaking" section or something like that?

**Comment by bushwhackr** [comment]
> Should that be listed under a "breaking" section or something like that?

I've updated it. Is it okay now?

**Review by YS-L — APPROVED** [review]

**Pull request merged**
