### PR TITLE
[DEV-2569] Use published featurebyte SDK in notebook tests

### PR DESCRIPTION
**Pull request by smillet15**
## Description

In order to get test coverage on changes that break backwards compatibility we can use the published version of the SDK when running the notebook tests.

## Type of Change

Label this pull request to place it under the correct category in Release Notes:

|        **Pull Request Label**         | **Category in Release Notes** |
|:-------------------------------------:|:-----------------------------:|
|       `enhancement`, `feature`        |          🚀 Features          |
| `bug`, `refactoring`, `bugfix`, `fix` |    🔧 Fixes & Refactoring     |
|       `build`, `ci`, `testing`        |    📦 Build System & CI/CD    |
|              `breaking`               |      💥 Breaking Changes      |
|            `documentation`            |       📝 Documentation        |
|            `dependencies`             |    ⬆️ Dependencies updates    |

## Checklist

- [x] I have read the [`CODE_OF_CONDUCT.md`](https://github.com/featurebyte/featurebyte/blob/main/CODE_OF_CONDUCT.md) and [`CONTRIBUTING.md`](https://github.com/featurebyte/featurebyte/blob/main/CONTRIBUTING.md) guides.
- [ ] I have written tests for the changes made.
- [ ] I have written docstrings in [NumpyDoc format](https://numpydoc.readthedocs.io/en/latest/format.html#docstring-standard)
- [x] I have labeled my Pull Request correctly

### CODE REVIEW

**Review by gee-senbong — APPROVED** [review]
@kchua78 Should we merge this PR first (even if the tests failed).

**Comment by kchua78** [comment]
> @kchua78 Should we merge this PR first (even if the tests failed). If i understood this correctly, we need to update the release package to fix this test.

In this case should we fix the backward compatibility?

**Comment by gee-senbong** [comment]
> > @kchua78 Should we merge this PR first (even if the tests failed). If i understood this correctly, we need to update the release package to fix this test.
> 
> In this case should we fix the backward compatibility?

Would be good if we can support the existing client without releasing a new version. Without this test coverage, it is hard to tell developer whether we break any other existing stuffs.. Anyway, I will wait this PR to get merged first before merging other major changes in featurebyte.

**Comment by smillet15** [comment]
I would rather release the fix first. I can test the fix with a build from the PR with the fix and then we can merge this right after to prevent future regressions.

**Comment by smillet15** [comment]
@jevonyeoh I dug into the deployment error that is now surfacing. First thing that is odd is if I run the same steps as the notebook in an ipython session, same virtualenv, backend, etc. the error doesn't surface. So I modified my install to at least get the full stacktrace:

```
---------------------------------------------------------------------------
RecordUpdateException                     Traceback (most recent call last)
Cell In[23], line 4
      2 import time
      3 time.sleep(1)
----> 4 deployment = feature_list.deploy(make_production_ready=True)
      5 deployment.enable()

File ~/Library/Caches/pypoetry/virtualenvs/featurebyte-Z7zrPce2-py3.10/lib/python3.10/site-packages/typeguard/__init__.py:1033, in typechecked.<locals>.wrapper(*args, **kwargs)
   1031 memo = _CallMemo(python_func, _localns, args=args, kwargs=kwargs)
   1032 check_argument_types(memo)
-> 1033 retval = func(*args, **kwargs)
   1034 try:
   1035     check_return_type(retval, memo)

File ~/Library/Caches/pypoetry/virtualenvs/featurebyte-Z7zrPce2-py3.10/lib/python3.10/site-packages/featurebyte/api/feature_list.py:1440, in FeatureList.deploy(self, deployment_name, make_production_ready, ignore_guardrails, use_case_name)
   1392 @typechecked
   1393 def deploy(
   1394     self,
   (...)
   1398     use_case_name: Optional[str] = None,
   1399 ) -> Deployment:
   1400     """
   1401     Create a deployment of a feature list. With a deployment, you can serve the feature list in production by
   1402     either online or batch serving.
   (...)
   1438     - [Deployment.get_online_serving_code](/reference/featurebyte.api.deployment.Deployment.get_online_serving_code/)
   1439     """
-> 1440     self.update(
   1441         update_payload={
   1442             "make_production_ready": make_production_ready,
   1443             "ignore_guardrails": ignore_guardrails,
   1444         },
   1445         allow_update_local=False,
   1446     )
   1447     use_case_id = UseCase.get(use_case_name).id if use_case_name else None
   1448     deployment_payload = DeploymentCreate(
   1449         name=deployment_name, feature_list_id=self.id, use_case_id=use_case_id
   1450     )

File ~/Library/Caches/pypoetry/virtualenvs/featurebyte-Z7zrPce2-py3.10/lib/python3.10/site-packages/typeguard/__init__.py:1033, in typechecked.<locals>.wrapper(*args, **kwargs)
   1031 memo = _CallMemo(python_func, _localns, args=args, kwargs=kwargs)
   1032 check_argument_types(memo)
-> 1033 retval = func(*args, **kwargs)
   1034 try:
   1035     check_return_type(retval, memo)

File ~/Library/Caches/pypoetry/virtualenvs/featurebyte-Z7zrPce2-py3.10/lib/python3.10/site-packages/featurebyte/api/api_object.py:478, in ApiObject.update(self, update_payload, allow_update_local, add_internal_prefix, url, skip_update_schema_check)
    476     raise DuplicatedRecordException(response=response)
    477 else:
--> 478     raise RecordUpdateException(response=response)

RecordUpdateException: {"id":"6d65dc38-1fc1-4d8e-8295-53cc07e8f373","status":"PENDING","output_path":null,"payload":{},"traceback":null,"start_time":null,"date_done":null,"progress":null}
```
Looking at the code now but wanted to at least share that in case the root cause is obvious to others.

**Comment by smillet15** [comment]
I wonder if it is the change to make it async that went in here: https://github.com/featurebyte/featurebyte/pull/1816

**Comment by gee-senbong** [comment]
> I wonder if it is the change to make it async that went in here: #1816

This PR (https://github.com/featurebyte/featurebyte/pull/1920) is created to fix this. Need up bump the featurebyte release package.

**Comment by smillet15** [comment]
https://github.com/featurebyte/infrastructure/pull/38 is now open to keep the workflow code in sync with the changes here.

**Review by bushwhackr — APPROVED** [review]
LGTM

**Pull request merged**
